name: Publish

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo '${{ toJSON(github) }}'
